package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GUI {

    private JPanel panel1;
    private JLabel number;
    private JLabel seed;
    private JTextField textNumber;
    private JTextField textSeed;
    private JLabel capacity;
    private JTextField textCapacity;
    private JButton button1;
    private JTextArea text1;
    private JTextArea text2;

    public GUI() {
        $$$setupUI$$$();

        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int N = Integer.parseInt(textNumber.getText());
                int Seed = Integer.parseInt(textSeed.getText());
                int capacity = Integer.parseInt(textCapacity.getText());

                Problem problem = new Problem(N, Seed, 1, 10);
                text2.setText(problem.toString());

                Result result = problem.Solve(capacity);
                text1.setText(result.toString2());
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("KnapsackGUI");
        frame.setContentPane(new GUI().panel1);
        frame.setPreferredSize(new Dimension(700, 600));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-7153424));
        panel1.setDoubleBuffered(false);
        panel1.setEnabled(true);
        panel1.setMaximumSize(new Dimension(1000000, 1000000));
        panel1.setPreferredSize(new Dimension(57, 141));
        capacity = new JLabel();
        capacity.setForeground(new Color(-16382458));
        capacity.setText("Capacity:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(capacity, gbc);
        textSeed = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textSeed, gbc);
        seed = new JLabel();
        seed.setForeground(new Color(-16382458));
        seed.setText("Seed:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(seed, gbc);
        textNumber = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textNumber, gbc);
        number = new JLabel();
        number.setEnabled(true);
        number.setForeground(new Color(-16382458));
        number.setText("Number:");
        number.setVerticalAlignment(0);
        number.setVerticalTextPosition(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 200);
        panel1.add(number, gbc);
        textCapacity = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textCapacity, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(button1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        text1 = new JTextArea();
        scrollPane1.setViewportView(text1);
        text2 = new JTextArea();
        text2.setRows(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(text2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
